# Generated by Django 4.2.14 on 2026-05-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('video_type', models.CharField(choices=[('cut', 'Video Cut'), ('song', 'Video Song'), ('event', 'Event Video'), ('celebration', 'Celebration Video'), ('ads', 'Advertisement')], max_length=20)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movies.movie')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video_type'], name='videos_vide_video_t_2e9eac_idx'), models.Index(fields=['movie'], name='videos_vide_movie_i_2c5b5b_idx')],
            },
        ),
    ]
