# Generated by Django 4.2.14 on 2026-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='folder_name',
            field=models.CharField(blank=True, help_text='Category/folder name for events and celebrations', max_length=255, null=True),
        ),
    ]
