# Generated by Django 4.2.14 on 2026-05-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_category',
            field=models.CharField(blank=True, help_text='Top-level category from Videos/ (e.g. Celebrations, Events, Adds, etc.)', max_length=50, null=True),
        ),
    ]
