# Generated by Django 4.2.14 on 2026-05-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('folder_type', models.CharField(choices=[('movie', 'Movie Photos'), ('event', 'Event Photos'), ('offline', 'Offline Photos')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_folders', to='movies.movie')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='photos.photofolder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='photos/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='photos/thumbnails/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.photofolder')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='photofolder',
            index=models.Index(fields=['folder_type'], name='photos_phot_folder__c6ac33_idx'),
        ),
        migrations.AddIndex(
            model_name='photofolder',
            index=models.Index(fields=['movie'], name='photos_phot_movie_i_820beb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='photofolder',
            unique_together={('name', 'folder_type')},
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['folder'], name='photos_phot_folder__0ba78a_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['order'], name='photos_phot_order_98a2b2_idx'),
        ),
    ]
