# Generated by Django 4.2.14 on 2026-05-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photofolder',
            name='path',
            field=models.CharField(blank=True, help_text='Full relative path from Photos root (e.g. Event/ADDS/Appy fizz)', max_length=500),
        ),
    ]
