# Generated by Django 4.2.14 on 2026-05-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photofolder_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photofolder',
            unique_together={('path', 'folder_type')},
        ),
    ]
