# Generated by Django 4.2.14 on 2026-05-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('music_director', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_url', models.URLField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('track_number', models.IntegerField(default=1)),
                ('plays', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_songs', to='movies.movie')),
            ],
            options={
                'ordering': ['track_number'],
                'indexes': [models.Index(fields=['movie'], name='audio_audio_movie_i_9ce8c9_idx'), models.Index(fields=['track_number'], name='audio_audio_track_n_9d80a7_idx')],
                'unique_together': {('movie', 'track_number')},
            },
        ),
    ]
