# Generated by Django 4.2.14 on 2026-05-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('release_year', models.IntegerField()),
                ('description', models.TextField()),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='movies/banners/')),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('box_office', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-release_year', 'title'],
                'indexes': [models.Index(fields=['slug'], name='movies_movi_slug_5ef9c7_idx'), models.Index(fields=['-release_year'], name='movies_movi_release_10e022_idx')],
            },
        ),
    ]
