# Generated by Django 4.2.14 on 2026-05-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(blank=True, help_text='Full movie file URL for playback', null=True),
        ),
    ]
