# Generated by Django 4.2.14 on 2026-05-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_release_10e022_idx',
        ),
        migrations.AddField(
            model_name='movie',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['sort_order'], name='movies_movi_sort_or_23c7f4_idx'),
        ),
    ]
